terminate called after throwing an instance of 'std::runtime_error'
  what():  Variable 'x' has already been declared
Aborted

exit status: 134
